# kpack Image CRD specs: https://github.com/pivotal/kpack/blob/master/docs/image.md
#  
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: nodejs-npm
  namespace: default
spec:
  builder:
    kind: ClusterBuilder
    name: tcserverbuilder
  imageTaggingStrategy: BuildNumber
  serviceAccount: default
  tag: lsilva.azurecr.io/nodejs-npm
  source:
    git:
      revision: main
      url: https://github.com/lsilvapvt/sample-nodejs-npm.git
